/*
 * This file is part of MFDStudio.
 * Project author: Benoit Fra
 * Repository: https://github.com/benoitfragit/MFDStudio
 */
#include "EditorTutorialData.h"

/**
 * @file
 * @brief Tutorial step metadata for the guided editor walkthrough.
 */

#include <array>
#include <cstddef>

namespace editor::tutorial
{
namespace
{
constexpr std::array<TutorialStepDefinition, static_cast<std::size_t>(TutorialStepId::Count)> kTutorialSteps {{
    {TutorialStepKind::UiAction,
     "Create the tutorial window",
     "Build a clean tutorial window from scratch so the rest of the walkthrough starts from a predictable document.",
     "menu_file",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the radar-track reticle",
     "Create the shared reticle template used later by the client when it spawns dynamic tutorial tracks.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the circle reticle",
     "Create a second template that will become the large circular mask on Page1.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the strobe cursor reticle",
     "Create a small cross-shaped reticle from one horizontal line, then append a vertical line so Page1 can later use it as a strobe cursor.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the aircraft reticle",
     "Create one dedicated `triangle` reticle named `mfd_tutorial_aircraft`. The tutorial reuses it twice later: once as the static ownship reference on Page1 and once as the distinct `Strobe1` template.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add the aircraft label primitive",
     "Still in `mfd_tutorial_aircraft`, append one `text` primitive so the alternative Page1 strobe can later demonstrate one exposed runtime-controlled primitive.",
     "library_append_primitive",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create Page1",
     "Author the first page of the tutorial. The page is seeded with the existing steering-cue binding so the next guided steps can focus on the radar-track layer and binding only.",
     "menu_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Select the Page1 title chrome",
     "On Page1, click `Select title chrome` in the page inspector. The dedicated title inspector is where you move, scale, hide, recolor, or restyle the generated page title without authoring a separate static reticle.",
     "page_select_title_chrome",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Frame the Page1 title",
     "In the Page1 title inspector, open `Decoration` and choose `Frame` so the generated title becomes one boxed heading. The same inspector also exposes line style, line width, color, visibility, and transform controls.",
     "page_title_decoration",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create RadarTrackLayer on Page1",
     "On Page1, in `Page layers`, click `Add layer`. The tutorial creates `RadarTrackLayer` so the radar-track dynamic reticle gets one dedicated runtime layer without changing the existing steering cue.",
     "inspector_add_radar_track_layer",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Allow the tutorial dynamic reticle on Page1",
     "On Page1, in `Dynamic reticles`, choose `mfd_tutorial_radar_track`, keep layer `RadarTrackLayer`, then click `Add`. Do not modify `inspired_steering_cue`: it is already configured on Page1.",
     "page_dynamic_template_mfd_tutorial_radar_track",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add the default Page1 strobe",
     "On Page1, keep the suggested strobe name `Default`, choose `mfd_tutorial_strobe_cursor`, then click `Add strobe`. This creates the default authored strobe that Page1 activates when it first loads.",
     "page_strobe_default",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add one alternative Page1 strobe",
     "Still on Page1, keep the suggested strobe name `Strobe1`, choose `mfd_tutorial_aircraft`, then click `Add strobe` again. Page1 now exposes one clearly distinct triangle-based alternative so the generated client can switch runtime strobe visuals without reusing the default cursor template.",
     "page_strobe_alternative",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Expose the alternative strobe label",
     "Select `aircraft_label` inside `mfd_tutorial_aircraft` and enable `Exposed` so the generated client can mutate one primitive on the active Page1 strobe without raw ids.",
     "primitive_exposed_checkbox",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Right-align the aircraft label",
     "Still on `aircraft_label`, open `Alignment` and choose `Right` so longer labels stay attached to the aircraft while new characters grow to the left.",
     "primitive_alignment",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Keep the strobe label upright",
     "Still on `aircraft_label`, disable both `Affected by reticle rotation` and `Affected by reticle scale`. The label will ignore parent strobe transforms until runtime code explicitly rotates or scales the primitive itself.",
     "primitive_reticle_rotation_checkbox",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add the aircraft reticle to Page1",
     "Instantiate `mfd_tutorial_aircraft` on Page1 so the page keeps one static ownship reference centered on `x = 0.0` and lowered to `y = -0.7`.",
     "library_add_to_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Rename the Page1 ownship reticle",
     "Still on Page1, rename the selected static reticle instance to `page1_ownship`. This changes only the page-local `Reticle id`; the shared template remains `mfd_tutorial_aircraft`.",
     "page_reticle_id",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add the circle reticle to Page1",
     "Instantiate the circle template on Page1 so you can immediately see how library templates become page reticles.",
     "library_add_to_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Clip everything outside the reticle",
     "Open the clipping context menu on the circle reticle and keep only the inside region to discover page-local masking.",
     "page_preview_clip_source",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add and hide an editor layer",
     "Create one extra runtime page layer and hide it in the editor to understand that preview visibility stays separate from runtime draw order.",
     "inspector_add_layer",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create Page2",
     "Add a second page so the tutorial client can demonstrate page switching.",
     "menu_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the progress-bar reticle",
     "Create a rectangle-based reticle for Page2, then append a second rectangle so the tutorial can animate a framed progress bar.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Expose the progress fill primitive",
     "Select the filling rectangle and mark it as exposed so the generated client API can resize and move it at runtime.",
     "primitive_exposed_checkbox",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add the progress bar to Page2",
     "Instantiate the progress-bar template on Page2 so the tutorial client can drive it through the generated page bindings.",
     "library_add_to_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Open the page context",
     "Open the View menu and enable Page context so you can compare the active page with the rest of the window without changing authored JSON.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Enable the layer inspector",
     "Open the View menu and enable Layer Inspector to inspect runtime page layers with their thumbnails and focus strip.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Enable the minimap",
     "Open the View menu and enable Minimap so navigation stays readable on larger authored pages.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Highlight reticle usages",
     "Keep one shared reticle template selected, open the View menu, and enable Highlight reticle usages to see where that template is reused.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Show the problems panel",
     "Open the View menu and enable Problems so validation diagnostics stay docked under the preview.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Hide a workspace panel",
     "Open the View menu and toggle Sidebar under Panels to discover that the side panels can be hidden to focus on the page. Re-open the View menu to bring it back whenever you need it.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Try fullscreen preview",
     "Open the View menu and toggle Fullscreen preview to enter it, then toggle it again to leave. The F11 key does the same from anywhere, so you can focus on the page canvas without the rest of the editor layout.",
     "page_preview_fullscreen",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Save the tutorial assets",
     "Write the authored tutorial window, pages, and reticles to disk once the guided editor tour is complete.",
     "menu_file",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Inspect page import",
     "Open the page import entry point from the editor menu so you know where shared page ingestion starts. You can cancel the native file dialog after locating it.",
     "menu_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Inspect page rename",
     "Open the global page rename workflow, review the scanned references, then close the popup without executing the rename.",
     "menu_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Inspect reticle rename",
     "Open the global reticle rename workflow, review the shared template references, then close the popup without executing the rename.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Inspect design export",
     "Open the design export workflow, review the export options and destination, then close the popup without exporting.",
     "menu_file",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::ReferenceDocument,
     "Open the tutorial follow-up guide",
     "Open the dedicated follow-up guide. It shows which authored assets to inspect, where `RadarTrackLayer`, `mfd_tutorial_radar_track`, and `mfd_tutorial_aircraft` end up on Page1, and which runtime files to open next.",
     "",
     "docs/tutorials/15_review_integrated_editor_tutorial_outputs.md",
     "The integrated coach now stays focused on authoring and editor actions. The detailed asset and runtime walkthrough lives in one doc so the editor no longer needs to replay large before/after code excerpts.",
     "Next"},
    {TutorialStepKind::ReferenceDocument,
     "Review the documentation path",
     "Open the tutorial index and continue with the runtime and generated-client documentation from there.",
     "",
     "docs/tutorials/README.md",
     "Continue with the mockup, the generated client API tutorial, then the generated-client standard and architecture notes.",
     "Finish"},
}};
} // namespace

mfd::ArrayView<const TutorialStepDefinition> Steps() noexcept
{
    return kTutorialSteps;
}

int StepCount() noexcept
{
    return static_cast<int>(kTutorialSteps.size());
}

bool IsUiStep(const TutorialStepDefinition& step) noexcept
{
    return step.kind == TutorialStepKind::UiAction;
}

bool IsReferenceDocumentStep(const TutorialStepDefinition& step) noexcept
{
    return step.kind == TutorialStepKind::ReferenceDocument;
}
} // namespace editor::tutorial
