/*
 * This file is part of MFDStudio.
 * Project author: Benoit Fra
 * Repository: https://github.com/benoitfragit/MFDStudio
 */
#include "EditorTutorialData.h"

/**
 * @file
 * @brief Tutorial step metadata for the guided editor walkthrough.
 */

#include <array>
#include <cstddef>

namespace editor::tutorial
{
namespace
{
constexpr std::array<TutorialStepDefinition, static_cast<std::size_t>(TutorialStepId::Count)> kTutorialSteps {{
    {TutorialStepKind::UiAction,
     "Create the tutorial window",
     "Build a clean tutorial window from scratch so the rest of the walkthrough starts from a predictable document.",
     "menu_file",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the radar-track reticle",
     "Create the shared reticle template used later by the client when it spawns dynamic tutorial tracks.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the circle reticle",
     "Create a second template that will become the large circular mask on Page1.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the strobe cursor reticle",
     "Create a small cross-shaped reticle from one horizontal line, then append a vertical line so Page1 can later use it as a strobe cursor.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create Page1",
     "Author the first page of the tutorial. The page is seeded with the existing steering-cue binding so the next guided steps can focus on the radar-track layer and binding only.",
     "menu_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create RadarTrackLayer on Page1",
     "On Page1, in `Page layers`, click `Add layer`. The tutorial creates `RadarTrackLayer` so the radar-track dynamic reticle gets one dedicated runtime layer without changing the existing steering cue.",
     "inspector_add_radar_track_layer",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Allow the tutorial dynamic reticle on Page1",
     "On Page1, in `Dynamic reticles`, choose `mfd_tutorial_radar_track`, keep layer `RadarTrackLayer`, then click `Add`. Do not modify `inspired_steering_cue`: it is already configured on Page1.",
     "page_dynamic_template_mfd_tutorial_radar_track",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Assign the Page1 strobe template",
     "On Page1, choose the small cross cursor as the page strobe so the runtime and the client both target a real authored strobe.",
     "page_strobe_template",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add the circle reticle to Page1",
     "Instantiate the circle template on Page1 so you can immediately see how library templates become page reticles.",
     "library_add_to_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Clip the reticle from the outside",
     "Open the clipping context menu on the circle reticle and keep only the outside region to discover page-local masking.",
     "page_preview_clip_source",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add and hide an editor layer",
     "Create one extra runtime page layer and hide it in the editor to understand that preview visibility stays separate from runtime draw order.",
     "inspector_add_layer",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create Page2",
     "Add a second page so the tutorial client can demonstrate page switching.",
     "menu_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Create the progress-bar reticle",
     "Create a rectangle-based reticle for Page2, then append a second rectangle so the tutorial can animate a framed progress bar.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Expose the progress fill primitive",
     "Select the filling rectangle and mark it as exposed so the generated client API can resize and move it at runtime.",
     "primitive_exposed_checkbox",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Add the progress bar to Page2",
     "Instantiate the progress-bar template on Page2 so the tutorial client can drive it through the generated page bindings.",
     "library_add_to_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Open the page context",
     "Open the page-preview View menu and enable Page context so you can compare the active page with the rest of the window without changing authored JSON.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Enable the layer inspector",
     "Open the page-preview View menu and enable Layer Inspector to inspect runtime page layers with their thumbnails and focus strip.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Enable the minimap",
     "Open the page-preview View menu and enable Minimap so navigation stays readable on larger authored pages.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Highlight reticle usages",
     "Keep one shared reticle template selected, open the page-preview View menu, and enable Highlight reticle usages to see where that template is reused.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Show the problems panel",
     "Open the page-preview View menu and enable Problems so validation diagnostics stay docked under the preview.",
     "page_preview_view_menu",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Try fullscreen preview",
     "Enter fullscreen preview, then leave it again, so you can focus on the page canvas without the rest of the editor layout.",
     "page_preview_fullscreen",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Save the tutorial assets",
     "Write the authored tutorial window, pages, and reticles to disk once the guided editor tour is complete.",
     "menu_file",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Inspect page import",
     "Open the page import entry point from the editor menu so you know where shared page ingestion starts. You can cancel the native file dialog after locating it.",
     "menu_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Inspect page rename",
     "Open the global page rename workflow, review the scanned references, then close the popup without executing the rename.",
     "menu_page",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Inspect reticle rename",
     "Open the global reticle rename workflow, review the shared template references, then close the popup without executing the rename.",
     "menu_reticle",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::UiAction,
     "Inspect design export",
     "Open the design export workflow, review the export options and destination, then close the popup without exporting.",
     "menu_file",
     nullptr,
     nullptr,
     nullptr},
    {TutorialStepKind::ReferenceDocument,
     "Open the tutorial follow-up guide",
     "Open the dedicated follow-up guide. It shows which authored assets to inspect, where `RadarTrackLayer` and `mfd_tutorial_radar_track` end up on Page1, and which runtime files to open next.",
     "",
     "docs/tutorials/15_review_integrated_editor_tutorial_outputs.md",
     "The integrated coach now stays focused on authoring and editor actions. The detailed asset and runtime walkthrough lives in one doc so the editor no longer needs to replay large before/after code excerpts.",
     "Next"},
    {TutorialStepKind::ReferenceDocument,
     "Review the documentation path",
     "Open the tutorial index and continue with the runtime and generated-client documentation from there.",
     "",
     "docs/tutorials/README.md",
     "Continue with the mockup, the generated client API tutorial, then the generated-client standard and architecture notes.",
     "Finish"},
}};
} // namespace

mfd::ArrayView<const TutorialStepDefinition> Steps() noexcept
{
    return kTutorialSteps;
}

int StepCount() noexcept
{
    return static_cast<int>(kTutorialSteps.size());
}

bool IsUiStep(const TutorialStepDefinition& step) noexcept
{
    return step.kind == TutorialStepKind::UiAction;
}

bool IsReferenceDocumentStep(const TutorialStepDefinition& step) noexcept
{
    return step.kind == TutorialStepKind::ReferenceDocument;
}
} // namespace editor::tutorial
