# This file is part of MFDStudio.
# Project author: Benoit Fra
# Repository: https://github.com/benoitfragit/MFDStudio
add_subdirectory(mfd_api)
add_subdirectory(mfd_runtime_api)
add_subdirectory(client_api_generator)
add_subdirectory(client_api)
add_subdirectory(hud)
add_subdirectory(mfd_window)
add_subdirectory(mfd_editor)
