# This file is part of MFDStudio.
# Project author: Benoit Fra
# Repository: https://github.com/benoitfragit/MFDStudio
add_subdirectory(mfd_framebuffer_stdout_plugin)
add_subdirectory(client_mockup)
add_subdirectory(client_mockup_minimal)
add_subdirectory(client_test_package)
add_subdirectory(client_tutorial)
add_subdirectory(offscreen_viewer)
