skinparam BackgroundColor transparent
skinparam Shadowing false
skinparam DefaultFontName Segoe UI
skinparam DefaultFontSize 15
skinparam dpi 170
skinparam ArrowColor #0f6985
skinparam ArrowThickness 1.3
skinparam RoundCorner 18

skinparam RectangleBackgroundColor #f7fbff
skinparam RectangleBorderColor #0f6985
skinparam RectangleFontColor #10263b

skinparam ParticipantBackgroundColor #f7fbff
skinparam ParticipantBorderColor #0f6985
skinparam ParticipantFontColor #10263b
skinparam SequenceParticipantBorderColor #0f6985
skinparam SequenceParticipantBackgroundColor #f7fbff
skinparam SequenceLifeLineBorderColor #8aa8bc
skinparam SequenceLifeLineBackgroundColor #eaf3f9
skinparam SequenceMessageAlign center

skinparam NoteBackgroundColor #eef7ff
skinparam NoteBorderColor #9db6c7
skinparam NoteFontColor #10263b

skinparam PackageBackgroundColor #f4f8fb
skinparam PackageBorderColor #9db6c7
skinparam PackageFontColor #14344a

skinparam ComponentBackgroundColor #f7fbff
skinparam ComponentBorderColor #0f6985
skinparam ComponentFontColor #10263b

skinparam ActivityBackgroundColor #f7fbff
skinparam ActivityBorderColor #0f6985
skinparam ActivityFontColor #10263b
