// This file is part of MFDStudio.
// Project author: Benoit Fra
// Repository: https://github.com/benoitfragit/MFDStudio
syntax = "proto3";

package mfd.transport;

import "mfd_commands.proto";

enum StrobeCaptureShape
{
  STROBE_CAPTURE_SHAPE_CIRCLE = 0;
  STROBE_CAPTURE_SHAPE_RECTANGLE = 1;
}

message StrobeCaptureArea
{
  StrobeCaptureShape shape = 1;
  float radius = 2;
  Vec2 size = 3;
}

message StrobeMagnetStatus
{
  bool enabled = 1;
  float radius = 2;
  float strength = 3;
  bool magnetized = 4;
  reserved 5;
  reserved "reticle";
  Vec2 target_position = 6;
  float distance = 7;
  uint64 runtime_reticle_id = 8;
}

message StrobeCaptureStatus
{
  reserved 1, 2;
  reserved "reticle", "template_id";
  string label = 3;
  string category = 4;
  Vec2 position = 5;
  float distance = 6;
  map<string, string> metadata = 7;
  uint64 runtime_reticle_id = 8;
  uint64 source_template_transport_id = 9;
}

message StrobeStatusFeedback
{
  uint32 sequence = 1;
  uint64 page_id = 2;
  uint64 strobe_id = 3;
  bool active = 4;
  Vec2 position = 5;
  StrobeCaptureArea capture = 6;
  StrobeMagnetStatus magnet = 7;
  optional StrobeCaptureStatus capture_result = 8;
  reserved 9;
}

message ActivePageFeedback
{
  uint32 sequence = 1;
  uint64 page_id = 2;
}

enum WindowLifecycleState
{
  WINDOW_LIFECYCLE_STATE_ALIVE = 0;
  WINDOW_LIFECYCLE_STATE_CLOSING = 1;
}

message WindowLifecycleFeedback
{
  uint32 sequence = 1;
  WindowLifecycleState state = 2;
}

message FeedbackEnvelope
{
  oneof payload
  {
    StrobeStatusFeedback strobe_status = 1;
    ActivePageFeedback active_page = 2;
    WindowLifecycleFeedback window_lifecycle = 3;
  }
}
